Advect ref
geodynamics/Rayleigh pull request #335
Opened 2021-10-29 19:53 UTC by feathern

This commit sets advect_reference_state to true by default.  As discussed in the issues section, this is probably the more intuitive default setting.  Note that with this commit, Rayleigh's internal benchmark routines now explicitly set this variable to false if one of the four benchmark modes are activated.   All input files have this variable set to false for consistency with the old default value that they assumed.

2021-10-30 00:33 UTC, illorenzo7 requested changes
Thanks Nick! I think this looks basically good, but did you forget to change advect_reference_state to .true. in Restore_Physics_Defaults() (line 213 of Controls.F90)?

2021-11-01 17:57 UTC, feathern commented
Good catch.  I just updated the PR.

2021-11-01 18:23 UTC, illorenzo7 approved these changes

2021-11-01 18:23 UTC, illorenzo7 commented
Great! All looks good now. Merging.

2021-11-01 18:23 UTC, merged