Fix bugs for custom diffusions
geodynamics/Rayleigh pull request #429
Opened 2022-12-25 05:04 UTC by illorenzo7

There was an issue in the logic for specifying custom scalar diffusions. Only nu_type, kappa_type, and eta_type were checked to be 3, with the result that if custom scalar diffusions were used, they might not be read from the binary file (unless reference_type was 4, in which case, the custom reference file had already been read). 

Similarly, for reference_type != 4 there was an indexing issue in temp_constants, that led to seg faults if one of the reference_types was 3. @feathern perhaps this is related to the issues you were seeing regarding custom reference and the scalar fields? 

Anyway, this pull request should fix these bugs. It incorporates my other pull requests (#427 and #426). 

Finally, there is an outstanding issue (that is supported by my preliminary testing) with custom diffusions (and again reference_type !=4 ). If one custom diffusion is used (but not all), then temp_functions will be overwritten by whatever was in the custom file. I think the diffusions in Rayleigh will be correct (and the code will run), but the output to the equation_coefficients file will be corrupt. I'm leaving this for now; there's enough to chat about with @feathern before making even more pull requests!

2022-12-31 20:34 UTC, illorenzo7 commented
Update: there was another bug in initializing ref%chi_buoyancy_coeff (the first index was zero instead of one). Someone more familiar with the scalar fields (@feathern or @cianwilson) should check on this to make sure everything is going as intended as far as the indexing is concerned. 

My (potentially flawed) interpretation: Say j = 1, 2, 3, ... , n_active_scalars. From what I understand, the user can set the constant multiplying the relevant function via the [11 + (j-1)*2]th constant. They can set the constant multiplying the buoyancy force (f_2) via the [12+(j-1)*2]th constant. This is at least what the code seems to reflect. 

It also seems that the buoyancy scalar diffusion constants are never set for reference_types = 1, 2, 3. Since I'm already thinking about this today, I will fix this in a separate pull request.

2023-01-04 23:50 UTC, illorenzo7 commented
Great! The same fix for #427 works here. I'll do the others now.

2023-01-05 18:29 UTC, feathern requested changes
This looks good save for two things.
1) The conflict ('object' vs. 'derived type') that needs to be resolved.  
2) As we discussed offline, please remove the comment about a bug that needs to be fixed (maybe just paste that into a brief issue note in Github).

2023-01-06 00:37 UTC, feathern approved these changes

2023-01-06 00:37 UTC, feathern commented
Great -- merging.

2023-01-06 00:37 UTC, merged