added dim/nondim input file pair
geodynamics/Rayleigh pull request #482
Opened 2023-06-23 00:35 UTC by illorenzo7

@feathern OK I have convinced myself that reference_type = 5 produces the same simulation as reference_type = 2, just rescaled. I added two input files to show how this works. One is the original "model_15" from our parameter survey and the other is the non-dimensional equivalent. 

Note the different conventions in Rossby number. 

I checked volume averaged output non-d numbers, differential rotation, meridional circulation, and radial energy flux balance and they all seem the same (after rescaling) up to < 1%. 

I think the 1%  difference comes from the heating being normalized slightly differently for ref type 5 (it doesn't get rescaled in Transport_Dependencies for ref type 5 to match the conductive flux loss out the boundaries). This makes the input Rayleigh numbers slightly different. 

Anyway, I think we're good to go! And these input files should show people how to use the new reference type.

2023-06-27 16:18 UTC, feathern requested changes
Hi Loren,
This looks great, but I was wondering if you could change the filenames and the header text so that we don't mention 'model 15' or the 'Boulder survey.'  Since that model isn't published yet, and since it's number might even change in the publication, it's probably best just to call these files 'anelastic_nondimensional' and 'anelastic_dimensional' or something like that.   Could you also reference the other file in the header?   Thanks!  I think this should just take a sec to change, and then I can approve/merge.

2023-06-28 19:45 UTC, illorenzo7 commented
@feathern Ok it should be good to go now.

2023-06-28 20:29 UTC, feathern approved these changes

2023-06-28 20:30 UTC, feathern commented
Looks great - merging!

2023-06-28 20:30 UTC, merged