Removed unused variables, module and apply suggestions from Ruff
geodynamics/Rayleigh pull request #569
Opened 2024-07-25 09:08 UTC by AlexKurek

2024-08-01 19:22 UTC, tukss requested changes
Thank you for the cleanup. I've reviewed the changes and suggested removing some parts entirely instead of just copying. For others I think keeping the commented variables is better.

The cleanup if the `if`s is particularly appreciated. Thanks!

2024-08-01 19:22 UTC, tukss commented on post_processing/rayleigh_diagnostics.py
> +    # iteration = np.zeros(1,dtype='int32')
These are just a copy & paste remnant from above. We should delete them.

```suggestion
```

2024-08-01 19:22 UTC, tukss commented on post_processing/rayleigh_diagnostics.py
> +    # ind = 0
We don't use these temporary buffers because we write to the file on the fly. So these can go.

```suggestion
```

2024-08-01 19:22 UTC, tukss commented on post_processing/rayleigh_diagnostics.py
> +    # iteration = np.zeros(1,dtype='int32')
These can go. Again just copy & paste.
```suggestion
```

2024-08-01 19:22 UTC, tukss commented on post_processing/rayleigh_diagnostics.py
> +            # nqfile = self.nq        # number of quantity codes in the file
We just use `self.nq` here. Let's keep just the comment.
```suggestion
            # number of quantity codes in the file
```

2024-08-02 02:55 UTC, tukss approved these changes
Thanks. Looks good to me now.

2024-08-02 02:58 UTC, merged

2024-08-02 09:52 UTC, AlexKurek commented
> The cleanup if the `if`s is particularly appreciated. Thanks!

This is easy if you use a linter, such as Ruff or Pylance. In VS Code you can even use both at the same time as plugins.